- name: Reload ssh
  become: true
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Reload ufw
  become: true
  ansible.builtin.command: ufw reload

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Restart CTFd
  community.docker.docker_compose_v2:
    project_src: /opt/ctfd
    state: restarted