- name: Provisioning lighthouse host
  hosts: lighthouse
  handlers:
    - name: Importing handlers
      ansible.builtin.import_tasks: ./handlers/basic-handlers.yaml

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  vars:
    # printf CC | xxd
    wireguard_port: 4343

  tasks:
    - name: Hardening servers
      ansible.builtin.import_tasks: ./tasks/hardening.yaml

    - name: Allowing udp {{ wireguard_port }} for wireguard
      community.general.ufw:
        rule: allow
        port: "{{ wireguard_port }}"
        proto: udp
        comment: wireguard port

    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_set: true
        state: present
        reload: true
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.default.forwarding
        - net.ipv6.conf.all.forwarding

    - name: Installing wireguard
      ansible.builtin.include_role:
        name: githubixx.ansible_role_wireguard
